# IAR EXTENSION
if(WIN32)
  set(EXT ".exe")
else()
  set(EXT "")
endif()

# EXECUTABLE EXTENSION
set(CMAKE_EXECUTABLE_SUFFIX ".elf")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# TARGET_TRIPLET

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER iccarm${EXT})
set(CMAKE_CXX_COMPILER iccarm${EXT})
set(CMAKE_ASM_COMPILER iasmarm${EXT})

# forward declaration with cache
set(CMAKE_C_FLAGS "" CACHE INTERNAL "c compiler flags")
set(CMAKE_CXX_FLAGS "" CACHE INTERNAL "c compiler flags")
set(CMAKE_EXE_LINKER_FLAGS "" CACHE INTERNAL "linker flags")
set(CMAKE_ASM_FLAGS "" CACHE INTERNAL "asm compiler flags")

# No prefix for static libs
SET(CMAKE_STATIC_LIBRARY_PREFIX_C "")
SET(CMAKE_STATIC_LIBRARY_SUFFIX_C ".a")

set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/${CMAKE_BUILD_TYPE})
set(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/${CMAKE_BUILD_TYPE})
